spring:
  application:
    name: convertcurrency
server:
  port: 8090  
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      refresh:
        enable: false 
 
logging:
   level:
    org.springframework.web: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      conversionFactorService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
