spring:
  application:
    name: convertcurrency
server:
  port: 8090  
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      refresh:
        enable: false 
 
logging:
   level:
    org.springframework.web: DEBUG       