apiVersion: apps/v1
kind: Deployment
metadata:
  name: convertcurrency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: convertcurrency
  template:
    metadata:
      labels:
        app: convertcurrency
    spec:
      containers:
      - name: convertcurrency
        image: microserviceapps/convertcurrency:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8090
